[base]
state_file = "~/.busy_engineers_state.toml"

[cloud9]
region = "us-east-2"
launch_url = "https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/quickcreate?templateUrl=https%3A%2F%2Fbusy-engineers-cfn.s3.us-east-2.amazonaws.com%2Fdocument-bucket-cloud9-bootstrap.yaml&stackName=BusyEngineersDocumentBucketEnvironment"

[website]
region = "us-east-2"
user_pool_name = "BusyEngineersUserPool"
identity_pool_name = "BusyEngineersIdentityPool"
user_pool_client_name = "BusyEngineersUserPoolClient"

[website.outputs]
user_pool_name = "BusyEngineersUserPoolOutput"
identity_pool_name = "BusyEngineersIdentityPoolOutput"
user_pool_client_name = "BusyEngineersUserPoolClientOutput"

[faythe_cmk]
region = "us-east-2"
alias = "FaytheCMK"

[walter_cmk]
region = "us-west-2"
alias = "WalterCMK"
